language: julia
os:
    - linux
julia:
    - 0.6
# env:
#   matrix:
#     - CC="gcc"
#     - CC="clang"
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterface.jl.git")'
    - julia -e 'Pkg.build("https://github.com/JuliaOpt/LinQuadOptInterface.jl.git")'
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("MathOptInterfaceGLPK")'
    - julia -e 'Pkg.test("MathOptInterfaceGLPK")'
after_success:
- echo $TRAVIS_JULIA_VERSION